<a href="https://colab.research.google.com/github/Wabaloo/PyTorchTest01/blob/main/ColabNotebook01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [2]:
my_list = [[1,2,3,4,5,6], [2,3,6,3,2]]
my_list

[[1, 2, 3, 4, 5, 6], [2, 3, 6, 3, 2]]

In [5]:
np1 = np.random.rand(2,4)
np1

array([[0.89701256, 0.03208004, 0.73899619, 0.24584437],
       [0.97921903, 0.59683108, 0.16662209, 0.18511753]])

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[-0.3656, -0.3961,  1.8182, -1.8267],
        [-1.6790,  1.9276, -1.0189, -1.8547],
        [-0.1558, -0.6373, -1.4066,  0.5180]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])